version: '3.7'

services:

  ka_master:
    build:
      context: .
    container_name: keepalived_master
    # restart: always
    volumes:
      - ./index_master.html:/var/www/html/index.nginx-debian.html
      - ./keepalived-master.conf:/etc/keepalived/keepalived.conf
    ports:
      - "8880:80"
    cap_add: 
      - NET_ADMIN
    networks:
      task_net:
        ipv4_address:
          172.198.222.10

  ka_backup:
    build:
      context: .
    container_name: keepalived_backup
    # restart: always
    volumes:
      - ./index_backup.html:/var/www/html/index.nginx-debian.html
      - ./keepalived-backup.conf:/etc/keepalived/keepalived.conf
    ports:
      - "8881:80"
    cap_add: 
      - NET_ADMIN
    networks:
      task_net:
        ipv4_address:
          172.198.222.20


networks:
  task_net:
    ipam:
      config:
        - subnet: 172.198.222.0/24
